sudo: required
servies:
  - docker

before_install:
  - docker build -t react_test -f ./client/Dockerfile.dev ./client

script:
  - docker run react_test npm test -- --coverage

after_success:
  - docker build -t multi_client ./client
  - docker build -t multi_nginx ./nginx
  - docker build -t multi_server ./server
  - docker build -t multi_worker ./worker

  # how to log into docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to dockerhub
  - docker push multi_client
  - docker push multi_nginx
  - docker push multi_server
  - docker push multi_worker